In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import os
import sys
sys.path.insert(0, "C:/workspace/data-science/libs")

from quickswap_extractor import get_swaps_history, list_to_tx_dict, swaps_history_to_df,\
                                get_reserves_history, list_to_reserves_dict, reserves_history_to_df,\
                                get_mints_history, list_to_mints_dict, mints_history_to_df,\
                                get_burns_history, burns_history_to_df, filter_swaps

Problem of current chosen subgraph is that it contains history till summer 2021

# WETH/DAI

In [2]:
weth_dai_contract_hash = '0x4a35582a710e1f4b2030a3f826da20bfb6703c09'

In [3]:
weth_dai_history = get_swaps_history(contract_hash=weth_dai_contract_hash)
all_weth_dai_history, other_weth_dai_history = filter_swaps(weth_dai_history)
print(len(weth_dai_history))
weth_dai_df = swaps_history_to_df(all_weth_dai_history)
weth_dai_df

  0%|          | 0/20000 [00:00<?, ?it/s]

list index out of range
0

AttributeError: 'DataFrame' object has no attribute 'timestamp'

In [ ]:
weth_dai_reserves_history = get_reserves_history(contract_hash=weth_dai_contract_hash)
weth_dai_reserves_df = reserves_history_to_df(weth_dai_reserves_history)
weth_dai_reserves_df

  1%|          | 1/100 [00:07<12:39,  7.67s/it]

,reserve0,reserve1,reserveUSD,dailyVolumeToken0,dailyVolumeToken1,date
0,2.000000e+00,7.000000e+02,6.946673e+02,0.000000,0.000000e+00,2020-10-08
1,7.081233e+00,2.413371e+03,4.537654e+03,0.081234,2.792531e+01,2020-10-09
2,6.014748e+00,2.088091e+03,4.299796e+03,0.129304,4.482321e+01,2020-10-10
3,1.976700e+00,7.084952e+02,1.437624e+03,0.289263,1.009511e+02,2020-10-11
4,5.200000e-17,1.935800e-14,3.961336e-14,0.069553,2.579408e+01,2020-10-12
...,...,...,...,...,...,...
272,6.846590e+03,1.297403e+07,2.597676e+07,1030.748425,1.939322e+06,2021-07-17
273,6.731566e+03,1.277032e+07,2.553403e+07,799.683585,1.544765e+06,2021-07-18
274,6.590887e+03,1.200127e+07,2.401244e+07,874.846714,1.613188e+06,2021-07-19
275,6.341991e+03,1.131404e+07,2.264479e+07,1801.156222,3.175610e+06,2021-07-20
276,5.631696e+03,1.108272e+07,2.215155e+07,1033.184607,1.933338e+06,2021-07-21

In [ ]:
weth_dai_mints_history = get_mints_history(contract_hash=weth_dai_contract_hash)
weth_dai_mints_df = mints_history_to_df(weth_dai_mints_history)
weth_dai_mints_df

 17%|█▋        | 17/100 [00:33<02:45,  1.99s/it]

         amount0      amount1    amountUSD   liquidity           timestamp
0       2.000000   700.000000   694.667279   37.416574 2020-10-08 22:20:58
1       4.000000  1393.036584  2805.505639   74.646531 2020-10-09 09:16:54
2       1.000000   348.259194   705.665115   18.661634 2020-10-09 15:30:58
3      13.000000  4527.369525  9133.292362  242.601244 2020-10-09 16:05:44
4       1.000000   348.259194   703.100031   18.661634 2020-10-09 16:52:36
...          ...          ...          ...         ...                 ...
16655   0.000662     1.298356     2.598020    0.000006 2021-07-21 17:11:53
16656   0.000011     0.020839     0.041703    0.005314 2021-07-21 17:12:43
16657   0.000063     0.123568     0.247236    0.158170 2021-07-21 17:20:41
16658   0.000358     0.704903     1.408994    0.057891 2021-07-21 17:23:15
16659   0.000202     0.397251     0.793962    0.000710 2021-07-21 17:24:59

[16660 rows x 5 columns]

In [ ]:
weth_dai_burns_history = get_burns_history(contract_hash=weth_dai_contract_hash)
weth_dai_burns_df = burns_history_to_df(weth_dai_burns_history)
weth_dai_burns_df.head(5)

  5%|▌         | 5/100 [00:09<02:59,  1.89s/it]

     amount0      amount1    amountUSD   liquidity           timestamp
0   1.000000   348.259194   702.843590   18.661634 2020-10-09 16:47:42
1  13.000000  4527.369525  9181.297382  242.601244 2020-10-09 17:46:18
2   1.002302   347.489260   721.959588   18.661634 2020-10-10 12:12:50
3   9.184591  3280.801774  6827.851247  173.571905 2020-10-11 07:21:04
4   0.052159    17.770315    38.078185    0.962618 2020-10-11 23:54:12

In [ ]:
weth_dai_df.to_csv('quick_weth_dai_swaps_df.csv')
weth_dai_reserves_df.to_csv('quick_weth_dai_reserves_df.csv')
weth_dai_mints_df.to_csv('quick_weth_dai_mints_df.csv')
weth_dai_burns_df.to_csv('quick_weth_dai_burns_df.csv')

# WMATIC/USDC

In [ ]:
wmatic_usdc_contract_hash = '0x4a35582a710e1f4b2030a3f826da20bfb6703c09'

In [ ]:
wmatic_usdc_history = get_swaps_history(contract_hash=wmatic_usdc_contract_hash)
all_wmatic_usdc_history, other_wmatic_usdc_history = filter_swaps(wmatic_usdc_history)
print(len(wmatic_usdc_history))
wmatic_usdc_df = swaps_history_to_df(all_wmatic_usdc_history)
wmatic_usdc_df

  2%|▏         | 396/20000 [14:35<12:02:08,  2.21s/it]

list index out of range

395191

,token_in,token_out,amount_in,amount_out,amount_usd,timestamp,sender,to,txd
0,WETH,DAI,0.005000,1.740412e+00,1.761443,2020-10-09 08:36:28,0xa5e0829caced8ffdd4de3c43696c57f7d7a678ff,0xf6e454836daf89466dd9aa98dc550b7afa183e4d,0x8ec3cb4089dbe061c55c044dc9645250111689e5f62a...
1,DAI,WETH,0.000145,4.138621e-07,0.000146,2020-10-09 14:14:02,0xa5e0829caced8ffdd4de3c43696c57f7d7a678ff,0x35d803f11e900fb6300946b525f0d08d1ffd4bed,0xd2b4ea89e0889f98a278354f5d4793bea5bfdab98505...
2,WETH,DAI,0.014510,5.027792e+00,4.646752,2020-10-09 22:31:20,0xa5e0829caced8ffdd4de3c43696c57f7d7a678ff,0xf04adbf75cdfc5ed26eea4bbbb991db002036bdd,0xd9afccdd77c1f1c7fd0aa9d36a44854c5237d2c7409c...
3,WETH,DAI,0.012924,4.460628e+00,4.138312,2020-10-09 22:35:10,0xa5e0829caced8ffdd4de3c43696c57f7d7a678ff,0xf04adbf75cdfc5ed26eea4bbbb991db002036bdd,0x11ffc0bcd42734e3479f740e5430a82925763d0e2c6a...
4,WETH,DAI,0.007915,2.723608e+00,2.533418,2020-10-09 22:36:46,0xa5e0829caced8ffdd4de3c43696c57f7d7a678ff,0xf04adbf75cdfc5ed26eea4bbbb991db002036bdd,0x873e9e2e6df287b931dbcc3f10a8f29fc5907e171ad8...
...,...,...,...,...,...,...,...,...,...
395185,WETH,DAI,0.010000,1.962116e+01,19.637336,2021-07-21 17:24:57,0xa5e0829caced8ffdd4de3c43696c57f7d7a678ff,0xf04adbf75cdfc5ed26eea4bbbb991db002036bdd,0x663a59fb7e308294a27c0fe8680f77ff50d9b5d86725...
395186,WETH,DAI,0.000202,3.972506e-01,0.397578,2021-07-21 17:24:59,0xa5e0829caced8ffdd4de3c43696c57f7d7a678ff,0x663462430834e220851a3e981d0e1199501b84f6,0x3f85851891ae4607d9fcae7b9a4283c1be89aa9bc9db...
395187,WETH,DAI,0.141649,2.779242e+02,278.163974,2021-07-21 17:25:01,0xa5e0829caced8ffdd4de3c43696c57f7d7a678ff,0x00b1200b448a3adaa10257fc415fca29d422e637,0x4b17940f6abfee8fecc340afd38802e2f85f7493406b...
395188,WETH,DAI,0.000136,2.674168e-01,0.267651,2021-07-21 17:25:07,0xa5e0829caced8ffdd4de3c43696c57f7d7a678ff,0x5ed3147f07708a269f744b43c489e6cf3b60aec4,0xffa01c7fd8df1adb6917cf9a5ac785776a60871c2835...
395189,WETH,DAI,0.000005,9.383045e-03,0.009391,2021-07-21 17:25:15,0xa5e0829caced8ffdd4de3c43696c57f7d7a678ff,0x5ed3147f07708a269f744b43c489e6cf3b60aec4,0x37e358bd51c6ef0e798c167cf1c891a81493d64e0901...

In [ ]:
wmatic_usdc_reserves_history = get_reserves_history(contract_hash=wmatic_usdc_contract_hash)
wmatic_usdc_reserves_df = reserves_history_to_df(wmatic_usdc_reserves_history)
wmatic_usdc_reserves_df

  1%|          | 1/100 [00:01<01:59,  1.21s/it]

,reserve0,reserve1,reserveUSD,dailyVolumeToken0,dailyVolumeToken1,date
0,2.000000e+00,7.000000e+02,6.946673e+02,0.000000,0.000000e+00,2020-10-08
1,7.081233e+00,2.413371e+03,4.537654e+03,0.081234,2.792531e+01,2020-10-09
2,6.014748e+00,2.088091e+03,4.299796e+03,0.129304,4.482321e+01,2020-10-10
3,1.976700e+00,7.084952e+02,1.437624e+03,0.289263,1.009511e+02,2020-10-11
4,5.200000e-17,1.935800e-14,3.961336e-14,0.069553,2.579408e+01,2020-10-12
...,...,...,...,...,...,...
272,6.846590e+03,1.297403e+07,2.597676e+07,1030.748425,1.939322e+06,2021-07-17
273,6.731566e+03,1.277032e+07,2.553403e+07,799.683585,1.544765e+06,2021-07-18
274,6.590887e+03,1.200127e+07,2.401244e+07,874.846714,1.613188e+06,2021-07-19
275,6.341991e+03,1.131404e+07,2.264479e+07,1801.156222,3.175610e+06,2021-07-20
276,5.631696e+03,1.108272e+07,2.215155e+07,1033.184607,1.933338e+06,2021-07-21

In [ ]:
wmatic_usdc_mints_history = get_mints_history(contract_hash=wmatic_usdc_contract_hash)
wmatic_usdc_mints_df = mints_history_to_df(wmatic_usdc_mints_history)
wmatic_usdc_mints_df

 17%|█▋        | 17/100 [00:30<02:28,  1.79s/it]

         amount0      amount1    amountUSD   liquidity           timestamp
0       2.000000   700.000000   694.667279   37.416574 2020-10-08 22:20:58
1       4.000000  1393.036584  2805.505639   74.646531 2020-10-09 09:16:54
2       1.000000   348.259194   705.665115   18.661634 2020-10-09 15:30:58
3      13.000000  4527.369525  9133.292362  242.601244 2020-10-09 16:05:44
4       1.000000   348.259194   703.100031   18.661634 2020-10-09 16:52:36
...          ...          ...          ...         ...                 ...
16655   0.000662     1.298356     2.598020    0.000006 2021-07-21 17:11:53
16656   0.000011     0.020839     0.041703    0.005314 2021-07-21 17:12:43
16657   0.000063     0.123568     0.247236    0.158170 2021-07-21 17:20:41
16658   0.000358     0.704903     1.408994    0.057891 2021-07-21 17:23:15
16659   0.000202     0.397251     0.793962    0.000710 2021-07-21 17:24:59

[16660 rows x 5 columns]

In [ ]:
wmatic_usdc_burns_history = get_burns_history(contract_hash=wmatic_usdc_contract_hash)
wmatic_usdc_burns_df = burns_history_to_df(wmatic_usdc_burns_history)
wmatic_usdc_burns_df.head(5)

  5%|▌         | 5/100 [00:06<02:05,  1.32s/it]

     amount0      amount1    amountUSD   liquidity           timestamp
0   1.000000   348.259194   702.843590   18.661634 2020-10-09 16:47:42
1  13.000000  4527.369525  9181.297382  242.601244 2020-10-09 17:46:18
2   1.002302   347.489260   721.959588   18.661634 2020-10-10 12:12:50
3   9.184591  3280.801774  6827.851247  173.571905 2020-10-11 07:21:04
4   0.052159    17.770315    38.078185    0.962618 2020-10-11 23:54:12

In [ ]:
wmatic_usdc_df.to_csv('quick_wmatic_usdc_swaps_df.csv')
wmatic_usdc_reserves_df.to_csv('quick_wmatic_usdc_reserves_df.csv')
wmatic_usdc_mints_df.to_csv('quick_wmatic_usdc_mints_df.csv')
wmatic_usdc_burns_df.to_csv('quick_wmatic_usdc_burns_df.csv')

# cxDOGE/cxETH

This contains history after Summer 2021 (beggining of 2022)

In [ ]:
cxdoge_cxeth_contract_hash = '0x96a523d3576b9b1dfee49aa73723f64a5b553720'

In [ ]:
cxdoge_cxeth_history = get_swaps_history(contract_hash=cxdoge_cxeth_contract_hash)
all_cxdoge_cxeth_history, other_cxdoge_cxeth_history = filter_swaps(cxdoge_cxeth_history)
print(len(cxdoge_cxeth_history))
cxdoge_cxeth_df = swaps_history_to_df(all_cxdoge_cxeth_history)
cxdoge_cxeth_df

  0%|          | 0/20000 [00:00<?, ?it/s]

list index out of range
0

AttributeError: 'DataFrame' object has no attribute 'timestamp'

In [ ]:
cxdoge_cxeth_reserves_history = get_reserves_history(contract_hash=cxdoge_cxeth_contract_hash)
cxdoge_cxeth_reserves_df = reserves_history_to_df(cxdoge_cxeth_reserves_history)
cxdoge_cxeth_reserves_df

  0%|          | 0/100 [00:00<?, ?it/s]

KeyError: 'reserve0'

In [ ]:
cxdoge_cxeth_mints_history = get_mints_history(contract_hash=cxdoge_cxeth_contract_hash)
cxdoge_cxeth_mints_df = mints_history_to_df(cxdoge_cxeth_mints_history)
cxdoge_cxeth_mints_df

  0%|          | 0/100 [00:00<?, ?it/s]

AttributeError: 'DataFrame' object has no attribute 'amount0'

In [ ]:
cxdoge_cxeth_burns_history = get_burns_history(contract_hash=cxdoge_cxeth_contract_hash)
cxdoge_cxeth_burns_df = burns_history_to_df(cxdoge_cxeth_burns_history)
cxdoge_cxeth_burns_df.head(5)

  0%|          | 0/100 [00:00<?, ?it/s]

AttributeError: 'DataFrame' object has no attribute 'amount0'

In [ ]:
cxdoge_cxeth_df.to_csv('quick_cxdoge_cxeth_swaps_df.csv')
cxdoge_cxeth_reserves_df.to_csv('quick_cxdoge_cxeth_reserves_df.csv')
cxdoge_cxeth_mints_df.to_csv('quick_cxdoge_cxeth_mints_df.csv')
cxdoge_cxeth_burns_df.to_csv('quick_cxdoge_cxeth_burns_df.csv')

NameError: name 'cxdoge_cxeth_df' is not defined