In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import pickle
import sys

# show all columns and all column content
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

# Collecting all tables

In [5]:
%%time
funding_rate_events_df = pd.read_csv("funding_rate_updated_events_pure.csv")
amm_positions_pure_df = pd.read_csv("amm_positions_pure.csv")
amm_pure_df = pd.read_csv("amm_pure_df.csv")
liquidation_events_df = pd.read_csv("liquidation_events_pure.csv")
positions_pure_df = pd.read_csv("positions_pure.csv")
margin_changed_events_df = pd.read_csv("margin_changed_events_pure.csv")
position_changed_events_df = pd.read_csv("position_changed_events_pure.csv")

Wall time: 2min 16s

# Check of all tables

## funding rate events

ok

In [4]:
funding_rate_events_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162960 entries, 0 to 162959
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                162960 non-null  object
 1   amm               162960 non-null  object
 2   rate              162960 non-null  int64
 3   underlying_price  162960 non-null  object
 4   block_number      162960 non-null  int64
 5   timestamp         162960 non-null  int64
dtypes: int64(3), object(3)
memory usage: 7.5+ MB

In [5]:
funding_rate_events_df

,id,amm,rate,underlying_price,block_number,timestamp
0,0xa397513e00f2cf81f720c4d0f42ddea3b2e5d9be641b4204ce838845748e0d67-3,0x0f346e19f01471c02485df1758cfd3d624e399b4,-187216719923324,19162225278134600000000,13509543,1607922060
1,0xc159f0f7ef82587f3c6b69374bab00b0d68e4afa41e112d9c1e17d25e4ae90bc-0,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,-134522057776142,587735679926363888888,13509543,1607922060
2,0xcd5dc4a5d66a4ab16abb3759aa88c1e6c0e957c75fd725a7f91e9dab373c1628-3,0x0f346e19f01471c02485df1758cfd3d624e399b4,-91694571357108,19095623159529838888888,13510257,1607925660
3,0xf354a25a613988571ebe671a15dc3ded1cc011e4e500ee4f92e52d1013e77b4b-0,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,10426395296687,584593715076127777777,13510257,1607925660
4,0x7435ec62031e473e1f9c5be987d6b2d1ab271a1b4f52d310c2feef84b85626b5-4,0x0f346e19f01471c02485df1758cfd3d624e399b4,-65957381468120,19088798206641350000000,13510972,1607929260
...,...,...,...,...,...,...
162955,0xccf3ef04013fe0adff88e50e18fbd5cfe83ca6241bfc1527ef7daaecf6f17812-159,0x922f28072babe6ea0c0c25ccd367fda0748a5ec7,22680882652130,426918830000000000,21335156,1648429260
162956,0xdc01382260c1685d6d9cbfe6f56357719357e0f42d3f3abe3ebcf60111833c5e-166,0xeac6cee594edd353351babc145c624849bb70b11,-30477628314975,11363982770000000000,21335156,1648429260
162957,0xde81e1e692f7e31642803675aa8e9764306b6b38bf67d90e7a960617b05b3174-142,0xb397389b61cbf3920d297b4ea1847996eb2ac8e8,30914040939901,5392831660000000000,21335156,1648429260
162958,0xe8ff282668ac7063b9ff8d8b999b609e6cb39a14e541ca00502a49ece9606608-182,0x26789518695b56e16f14008c35dc1b281bd5fc0e,-9538806566110,384084440000000000,21335156,1648429260
162959,0xfcfa841e86a53a9ccb1a4906acd52fa3d79905dc28de0d9449cabaf05b6f4670-152,0xf559668108ff57745d5e3077b0a7dd92ffc6300c,18107839584690,3949340160000000000,21335156,1648429260

## amm positions

In [6]:
amm_positions_pure_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17840 entries, 0 to 17839
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   17840 non-null  object
 1   amm                  17840 non-null  object
 2   trader               17840 non-null  object
 3   margin               17840 non-null  object
 4   position_size        17840 non-null  object
 5   open_notional        17840 non-null  object
 6   trading_volume       17840 non-null  object
 7   leverage             17840 non-null  object
 8   entry_price          17840 non-null  object
 9   realized_pnl         17840 non-null  object
 10  unrealized_pnl       17840 non-null  object
 11  funding_payment      17840 non-null  object
 12  fee                  17840 non-null  object
 13  bad_debt             17840 non-null  object
 14  liquidation_penalty  17840 non-null  object
 15  total_pnl_amount     17840 non-null  object
 16  block_number         17840 non-null  int64
 17  timestamp            17840 non-null  int64
dtypes: int64(2), object(16)
memory usage: 2.5+ MB

In [7]:
amm_positions_pure_df

,id,amm,trader,margin,position_size,open_notional,trading_volume,leverage,entry_price,realized_pnl,unrealized_pnl,funding_payment,fee,bad_debt,liquidation_penalty,total_pnl_amount,block_number,timestamp
0,0x0f346e19f01471c02485df1758cfd3d624e399b4-0x43bd90e4cc93d6e40580507102cc7b1bc8a25284,0x0f346e19f01471c02485df1758cfd3d624e399b4,0x43bd90e4cc93d6e40580507102cc7b1bc8a25284,0,0,0,382451121351883997283,0,0,1235316261887316051,0,46527106654655277,382451121351883996,0,0,806338033880776778,13517550,1607963895
1,0x0f346e19f01471c02485df1758cfd3d624e399b4-0x9602686bf53a17baed60c48ba34ed4219a532381,0x0f346e19f01471c02485df1758cfd3d624e399b4,0x9602686bf53a17baed60c48ba34ed4219a532381,0,0,0,33226635926189772552590,0,0,17792407023400932044,0,-114614332899406570,33226635926189772547,0,0,-15319614569889433933,13527667,1608016775
2,0x0f346e19f01471c02485df1758cfd3d624e399b4-0x7a0cb9bb153a9891d1852875af9bcb65e716038e,0x0f346e19f01471c02485df1758cfd3d624e399b4,0x7a0cb9bb153a9891d1852875af9bcb65e716038e,0,0,0,973557806096639491963,0,0,3877193629795939317,0,32557905398584567,973557806096639490,0,0,2871077918300715260,13536482,1608061915
3,0x0f346e19f01471c02485df1758cfd3d624e399b4-0x2823819fe9e6c8ad24daa61777089dcbffdc59bc,0x0f346e19f01471c02485df1758cfd3d624e399b4,0x2823819fe9e6c8ad24daa61777089dcbffdc59bc,0,0,0,3937220110690488022500,0,0,-102083451512069077700,0,-4032120232683888232,1917568329589209472,0,93705501679535757772,-193674401288510156712,13549293,1608126640
4,0x0f346e19f01471c02485df1758cfd3d624e399b4-0xe620d45518c7147db9b6c42442c80cc68343e4e1,0x0f346e19f01471c02485df1758cfd3d624e399b4,0xe620d45518c7147db9b6c42442c80cc68343e4e1,0,0,0,5990847695616847422359,0,0,58838955816847422359,0,0,5990847695616847422,0,0,52848108121230574937,13549332,1608126840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17835,0x0f346e19f01471c02485df1758cfd3d624e399b4-0xa2b2001f3ad95a27a0ff81fce8ee403c9906fa39,0x0f346e19f01471c02485df1758cfd3d624e399b4,0xa2b2001f3ad95a27a0ff81fce8ee403c9906fa39,1097010611351271247680,198811630127162408,9175208202790210730191,7975503319559557342213477,4328366619445398353,46150258900455836907456,2811640953619222185310,169334663817499376126,-288422013534877733970,7975503319559557341317,0,0,-4875440352405457422037,21334982,1648428345
17836,0x80daf8abd5a6ba182033b6464e3e39a0155dcc10-0x75823b65f3ddcbceba54e2e83db971bfdd27f02b,0x80daf8abd5a6ba182033b6464e3e39a0155dcc10,0x75823b65f3ddcbceba54e2e83db971bfdd27f02b,666666666666666666667,-119189603380592228108,2000000000000000000001,2378842071403106146933006,3000000000000000000,16779987039756037654,8311108803928429955849,0,16725063754177705065,2378842071403106146643,0,0,5915541668771146104141,21335035,1648428625
17837,0x838b322610bd99a449091d3bf3fba60d794909a9-0xd94606128b20680539a719b07bca6cbc30786a28,0x838b322610bd99a449091d3bf3fba60d794909a9,0xd94606128b20680539a719b07bca6cbc30786a28,0,0,0,54069694491390341028753457,0,0,127519750585951523209905,0,-282321289709136345974,54064509898871660517803,0,64807406483506317235,73672754570305492720841,21335037,1648428635
17838,0x16a7ecf2c27cb367df36d39e389e66b42000e0df-0x6ea70c3ee5d8a11c448df348fc15779b843b7d3d,0x16a7ecf2c27cb367df36d39e389e66b42000e0df,0x6ea70c3ee5d8a11c448df348fc15779b843b7d3d,26308938694829024181247,-194776662743967392295,23406450754194777511212,35990202050809164361300,889676737845577724,120170714624895277861,-1802200814950533105608,-9435510925897522078239,-812526512266205095129,35990202050809164356,0,0,-1025664504735137174835,21335051,1648428710
17839,0x6de775aabeeede8efdb1a257198d56a3ac18c2fd-0x8d956c284e59e107e79927daf0753b40009a6735,0x6de775aabeeede8efdb1a257198d56a3ac18c2fd,0x8d956c284e59e107e79927daf0753b40009a6735,7658473066026794730009,4135130963881609111724,87523528353144047787305,469323278735300086620334,4008270372043990810,21165841932848125052,-49253797019332755872193,-11047300639032951025835,-14096033181282918786394,469323278735300085894,0,0,-35627087116785137171693,21335131,1648429130

## amm

In [8]:
amm_pure_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      19 non-null     object
 1   position_balance        19 non-null     object
 2   open_interest_size      19 non-null     object
 3   open_interest_notional  19 non-null     object
 4   trading_volume          19 non-null     object
 5   quote_asset_reserve     19 non-null     object
 6   base_asset_reserve      19 non-null     object
 7   block_number            19 non-null     int64
 8   timestamp               19 non-null     int64
dtypes: int64(2), object(7)
memory usage: 1.5+ KB

In [9]:
amm_pure_df

,id,position_balance,open_interest_size,open_interest_notional,trading_volume,quote_asset_reserve,base_asset_reserve,block_number,timestamp
0,0x0f346e19f01471c02485df1758cfd3d624e399b4,149356259032261592310,166012334896747841690,6431649878569804882753980,3207493744873787499689376455,13584728439337145677641199,350643740967738407690,21122752,1647352335
1,0x16a7ecf2c27cb367df36d39e389e66b42000e0df,-18312211315882106544926,18419138257520536739862,2136620037872382261823992,2238137054124585607454308028,4470115248320452721824428,38312211315882106544926,21122861,1647352880
2,0x187c938543f2bde09fe39034fe3ff797a3d35ca0,-4481308318434705168953247,4566422810159486148459985,0,1669866025001437973828885823,5596466784484574839284497,14481308318434705168953247,21122855,1647352850
3,0x26789518695b56e16f14008c35dc1b281bd5fc0e,-7754592760824474354357911,7770905351559403427798249,0,1524691706004846787673660221,4588866334336389329479071,17754592760824474354357911,21122858,1647352865
4,0x33fbaefb2dcc3b7e0b80afbb4377c2eb64af0a3a,-20502525358674345534825,20633466512015099125223,2063346651201509912522300,1997601714154883211810269483,3820933091167299952249301,38102525358674345534825,21122798,1647352565
5,0x6de775aabeeede8efdb1a257198d56a3ac18c2fd,-2510510918083939568214,201470491909601449107284,3424998362463224634823828,2684351884942255044416551417,5221306179432915090956091,302510510918083939568214,21122859,1647352870
6,0x7b479a0a816ca33f8eb5a3312d1705a34d2d4c82,-46744937469036023889771,54850493547935378165681,2248870235465350504792921,1152072824183342561216224439,4462380812290072135044241,107744937469036023889771,21122850,1647352825
7,0x80daf8abd5a6ba182033b6464e3e39a0155dcc10,-122331032227543548835744,123352672018771764082434,1603584736244032933071642,2487402390874899255257323199,5536415327255005998508061,422331032227543548835744,21122856,1647352855
8,0x838b322610bd99a449091d3bf3fba60d794909a9,28461552388827125306238,35085283638372209011228,1403411345534888360449120,964356300673371023859599860,9172778063360462886001626,226538447611172874693762,21122852,1647352835
9,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,10392951430740057336400,10551767737836819888988,26738179447678501598695592,7526235383453880625944174158,24346290987682355562738696,9607048569259942663600,21122854,1647352845
10,0x922f28072babe6ea0c0c25ccd367fda0748a5ec7,-5897143318463342644302944,5897687779358965230570456,0,1853578734729609551196395562,4376384356260286929175892,13397143318463342644302944,21122860,1647352875
11,0xab08ff2c726f2f333802630ee19f4146385cc343,-727441101496216447892344,1623106697721701392071412,1623106697721701392071412,2765886849134438109851815999,6508470704357813496667453,3427441101496216447892344,21122858,1647352865
12,0xb397389b61cbf3920d297b4ea1847996eb2ac8e8,-327090950999922067470362,329052601053502659386148,987157803160507978158444,1519251519614368834383864796,2424050287404304951205124,627090950999922067470362,21122779,1647352470
13,0xb48f7accc03a3c64114170291f352b37eea26c0b,-1136370137681665159566,1156360572426394488800,2034038246898027905799200,1090246983116625977891826601,4989888006885248070524199,2836370137681665159566,21122860,1647352875
14,0xd41025350582674144102b74b8248550580bb869,-29215750837513535677,39370277952936482991,720357975704878829286327,2190909023016108151584683329,4194127133442458167597725,229215750837513535677,21122859,1647352870
15,0xeac6cee594edd353351babc145c624849bb70b11,-255241645741454566345707,257404747943478622456071,2059237983547828979648568,1835874695058155567674911463,4490547142766943331392871,540241645741454566345707,21122857,1647352860
16,0xf559668108ff57745d5e3077b0a7dd92ffc6300c,-697313589682622386646444,698815827908456072272100,1397631655816912144544200,2104464716875319818840008710,3252674152934059956146982,1157313589682622386646444,21122853,1647352840
17,0xf9e30f08a738620bc2331f728de4dac7937888d3,186253146692553665527357,531977390616066379706985,0,73506818114456456337458,0,0,16516492,1623405540
18,0xfcae57db10356fcf76b6476b21ac14c504a45128,-552590803720158927068460,732763409526981019049590,2198290228580943057148770,2125231792256191111231023006,6127278538828577556845654,1652590803720158927068460,21122826,1647352705

## liquidations

ok

In [10]:
liquidation_events_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38934 entries, 0 to 38933
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 38934 non-null  object
 1   trader             38934 non-null  object
 2   amm                38934 non-null  object
 3   position_notional  38934 non-null  object
 4   position_size      38934 non-null  object
 5   liquidation_fee    38934 non-null  object
 6   liquidator         38934 non-null  object
 7   bad_debt           38934 non-null  object
 8   block_number       38934 non-null  int64
 9   timestamp          38934 non-null  int64
dtypes: int64(2), object(8)
memory usage: 3.0+ MB

In [11]:
liquidation_events_df

,id,trader,amm,position_notional,position_size,liquidation_fee,liquidator,bad_debt,block_number,timestamp
0,0xc4889e27cec24728d805bc53ea69ec9771c85bfce825563cc0b55c73ce8bb056-6,0x2823819fe9e6c8ad24daa61777089dcbffdc59bc,0x0f346e19f01471c02485df1758cfd3d624e399b4,2019651781101278550100,100000000000000000,25245647263765981876,0x5a0f7edceda1b0267a15544b883c9e749405585a,0,13549293,1608126640
1,0xad73d00c92a596d4f2ff993a0739ceadf2aebb6f44492fcb6990d2ad112c7ec6-6,0xfc4656e9b916b2cbc4aa0e870ba4d9a46c8b59a9,0x0f346e19f01471c02485df1758cfd3d624e399b4,5091745730336835779492,250000000000000000,63646821629210447243,0x5a0f7edceda1b0267a15544b883c9e749405585a,0,13549484,1608127605
2,0x6ed6cba6b46fb7fc560dc5c8ee9a1a8d3ec5cdb5ebdfaf8d8eac65086c876b6e-9,0xbeb0d8f05c5f923b80690657da949cebd9a2bfbc,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,5698613657512103778707,8822341982986002606,71232670718901297233,0x5a0f7edceda1b0267a15544b883c9e749405585a,0,13556301,1608164255
3,0x334432dee6a350dd6b13805babe635160fd4c9f078c6fd9543e5eadce0546602-16,0x3f84e391ea8dc12946e17d1d85cdf0b35d4fe650,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,648204518143780021975,1000000000000000000,8102556476797250274,0x5a0f7edceda1b0267a15544b883c9e749405585a,0,13556346,1608164505
4,0xa1b2fc6d459f6d32fe405388fe8f766925cd76e58e0da903981bee8623fd0ae2-6,0x3871dffe795145bcce5e24793a82d93993550843,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,10363661814828051856,15467118125853643,129545772685350648,0x5a0f7edceda1b0267a15544b883c9e749405585a,0,13563166,1608201405
...,...,...,...,...,...,...,...,...,...,...
38929,0xcac97f34ca96bdbb202a91d0af0ac8061dea696cc4d1ef6c6d2f61ad8594da79-21,0xe4201eaeb2f31d0d8321aef77936aa403a4ccc25,0x0f346e19f01471c02485df1758cfd3d624e399b4,12005189873900360789,256643457395252,75032436711877254,0x5a0f7edceda1b0267a15544b883c9e749405585a,0,21334332,1648424915
38930,0xd3ac193aa02ce2175a123aee3d9c46cf9292e728bdbbf0d266da420cad486242-13,0xbf37a2f4f1eafe152e8336465cfaad1fda44b588,0x0f346e19f01471c02485df1758cfd3d624e399b4,8440126452644021930,180430321350058,52750790329025137,0x5a0f7edceda1b0267a15544b883c9e749405585a,0,21334356,1648425040
38931,0xc58cfe4a6984dc0089239faf0418f47289781061955c12b36cf924b2b122b0a1-8,0xc0f872a7127bdc6d98af04899d1a1d22376c7b6b,0x6de775aabeeede8efdb1a257198d56a3ac18c2fd,218105728267334776386,9688481976251832266,1363160801670842352,0x07cf2d1ba50f015571a6f1a5493b69781fdcd4ec,0,21334846,1648427625
38932,0xbb2bf7e3623b56a421a264b0e2f874dfeb009d10ab58a4182cca366d1f8693b3-27,0x57e15754dfd25fa5b59e41d7a2d16176bf8b06f0,0x0f346e19f01471c02485df1758cfd3d624e399b4,483079754411736317766,10221717804593637,3019248465073351986,0x9dde2f1e44f2518cbfbf79ad6ed0ed24048c0c08,0,21334889,1648427855
38933,0xab1a4e93c35fa3c52380cfaea47acf589ec96d3c0e4786d5a0ce6048f97d0399-11,0xc0f872a7127bdc6d98af04899d1a1d22376c7b6b,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,711861510936084501366,215539611021280179,4449134443350528133,0x07cf2d1ba50f015571a6f1a5493b69781fdcd4ec,0,21334943,1648428140

## positions

In [12]:
positions_pure_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10050 entries, 0 to 10049
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   10050 non-null  object
 1   trader               10050 non-null  object
 2   margin               10050 non-null  object
 3   open_notional        10050 non-null  object
 4   trading_volume       10050 non-null  object
 5   leverage             10050 non-null  object
 6   realized_pnl         10050 non-null  object
 7   unrealized_pnl       10050 non-null  object
 8   funding_payment      10050 non-null  object
 9   fee                  10050 non-null  object
 10  bad_debt             10050 non-null  object
 11  liquidation_penalty  10050 non-null  object
 12  total_pnl_amount     10050 non-null  object
 13  block_number         10050 non-null  int64
 14  timestamp            10050 non-null  int64
dtypes: int64(2), object(13)
memory usage: 1.2+ MB

In [13]:
positions_pure_df

,id,trader,margin,open_notional,trading_volume,leverage,realized_pnl,unrealized_pnl,funding_payment,fee,bad_debt,liquidation_penalty,total_pnl_amount,block_number,timestamp
0,0x7a0cb9bb153a9891d1852875af9bcb65e716038e,0x7a0cb9bb153a9891d1852875af9bcb65e716038e,0,0,973557806096639491963,0,3877193629795939317,0,32557905398584567,973557806096639490,0,0,2871077918300715260,13536482,1608061915
1,0x2823819fe9e6c8ad24daa61777089dcbffdc59bc,0x2823819fe9e6c8ad24daa61777089dcbffdc59bc,0,0,3937220110690488022500,0,-102083451512069077700,0,-4032120232683888232,1917568329589209472,0,93705501679535757772,-193674401288510156712,13549293,1608126640
2,0xa163e3e565d67c71778060f9dc907cf92d13ce4a,0xa163e3e565d67c71778060f9dc907cf92d13ce4a,0,0,102774136437962910937,0,3649733037962910937,0,44781352758163660,102774136437962910,0,0,3502177548766784367,13551609,1608138915
3,0xfe32a37f15ee4a4b59715530e5817d1322b9df80,0xfe32a37f15ee4a4b59715530e5817d1322b9df80,0,0,12424222389186808956301,0,20951143501444494719,0,242877886406422400,12424222389186808955,0,0,8284043225851263364,13552780,1608145190
4,0xe620d45518c7147db9b6c42442c80cc68343e4e1,0xe620d45518c7147db9b6c42442c80cc68343e4e1,0,0,18393392652043224887193,0,203452026043224887193,0,1076482803524146425,18393392652043224886,0,0,183982150587657515882,13556960,1608167825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10045,0xbb993b8fd7f725e6fa294610647242537b6994cc,0xbb993b8fd7f725e6fa294610647242537b6994cc,756536402862133231880,0,922391681987619333434104,0,460000815905207220610,0,-1366011032848633233010,915695679451090785877,0,83700031706606841658,826616137596142826085,21334870,1648427755
10046,0xc68ce3729890460377ead8a68eb2899a440a3a15,0xc68ce3729890460377ead8a68eb2899a440a3a15,77539823978695278401297,119446051121733193187744,607692558542691872785230,1540447798212077508,-37147803860509040772376,2237896160529939168101,-15396342250001169249452,516946205176661594776,9016979023828432772618,9255385420243058984253,-22506814212099159329335,21334877,1648427790
10047,0x57e15754dfd25fa5b59e41d7a2d16176bf8b06f0,0x57e15754dfd25fa5b59e41d7a2d16176bf8b06f0,358571354538632804640,1190126483852196169118,3232105804741846175399,3319078528689248255,-191053146714042344517,-259299443938957282914,16706417729801773651,2115589570940000000,0,13956452922523077192,-223831606937307195360,21334889,1648427855
10048,0x71065288f0604a8052476ae73038875be13efa72,0x71065288f0604a8052476ae73038875be13efa72,93525353742092157270348,147688454195035172747618,645335026799156888212564,1579127458873927695,-34229495131417603144956,-38854080892121966921700,-26734600853353328572266,645335026799156888112,0,0,-8140229304863431460802,21334900,1648427910
10049,0x75823b65f3ddcbceba54e2e83db971bfdd27f02b,0x75823b65f3ddcbceba54e2e83db971bfdd27f02b,666666666666666666667,2000000000000000000001,2378842071403106146933006,3000000000000000000,8311108803928429955849,0,16725063754177705065,2378842071403106146643,0,0,5915541668771146104141,21335035,1648428625

## margin changed

ok

In [14]:
margin_changed_events_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3240767 entries, 0 to 3240766
Data columns (total 7 columns):
 #   Column           Dtype
---  ------           -----
 0   id               object
 1   sender           object
 2   amm              object
 3   amount           object
 4   funding_payment  object
 5   block_number     int64
 6   timestamp        int64
dtypes: int64(2), object(5)
memory usage: 173.1+ MB

In [15]:
margin_changed_events_df

,id,sender,amm,amount,funding_payment,block_number,timestamp
0,0xb359abc9906d7ba2e72fc0339557bc816c722740647dc6e31563b02be819d088-2,0x3f84e391ea8dc12946e17d1d85cdf0b35d4fe650,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,10000000000000000000,0,13510771,1607928240
1,0x2064d36e819daa34a372e5433ef81dde733d740a79529cf9c2d2df2f4e9d449b-1,0x3f84e391ea8dc12946e17d1d85cdf0b35d4fe650,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,-20000000000000000000,0,13510776,1607928265
2,0x72cc2a320945e33eddbb46b25a892c2be69698f10e838e95990b6ebeab6c3e90-1,0x5bea7caa02142ba59885466757e1112819731f09,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,-34040000000000000000,0,13510801,1607928390
3,0x6d177d58cfce6bd165e9f52960e5635f48ae3e5eb42f5496402fe748c7807e2e-2,0x5bea7caa02142ba59885466757e1112819731f09,0x0f346e19f01471c02485df1758cfd3d624e399b4,35810000000000000000,0,13510808,1607928425
4,0xdbc9e3d258653d7afa8a3e7cfd865095dabdc04827e6da6b3812a8d8bfb91966-1,0x069a67b8f965d02d095be12ae55e31e769692df4,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,-1000000000000000000,0,13510998,1607929395
...,...,...,...,...,...,...,...
3240762,0xc1ef8d0f917c0cc3d4d00d9a991269991a5deaef80fc7d2c9cbd6d515c0564d3-5,0xa7b6679232241b3a8cb819faeed876f3fe10d50b,0x922f28072babe6ea0c0c25ccd367fda0748a5ec7,-132792719000000000000,0,21335175,1648429365
3240763,0xe68178f00f6aa74bc83270083b279d8c8529ac2cd08f50c4d13e2e72f0138694-3,0x72dd2ce1b88f2cbcee606ec2ede14cf03563e08d,0x26789518695b56e16f14008c35dc1b281bd5fc0e,-1365964154416574081707,0,21335175,1648429365
3240764,0x1fd7c3f2fd11d5a7b7c923c406a802329b7e72c0b7002e17c7f3f1f4150aa8c3-1,0xce7e86725fa9ef1f5cd0f266bf5d48af1686f445,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,-1971047353340394121898,0,21335179,1648429385
3240765,0x698f3398ca9e5f5c083f1ffd1aacc03cc23f860f863339bc4a4156e5402a1e0f-1,0xce7e86725fa9ef1f5cd0f266bf5d48af1686f445,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,-1971888372803269121366,0,21335185,1648429415
3240766,0x7c1e3dca38a32ad816cbcc970ff108908dc027dbaf70b89859380d95f0ffa19f-1,0x72dd2ce1b88f2cbcee606ec2ede14cf03563e08d,0x26789518695b56e16f14008c35dc1b281bd5fc0e,-2666899129479347831963,0,21335188,1648429430

## position changed

ok

In [3]:
position_changed_events_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568514 entries, 0 to 9568513
Data columns (total 16 columns):
 #   Column                   Dtype
---  ------                   -----
 0   id                       object
 1   trader                   object
 2   amm                      object
 3   margin                   object
 4   position_notional        object
 5   exchanged_position_size  object
 6   fee                      object
 7   position_size_after      object
 8   realized_pnl             object
 9   unrealized_pnl_after     object
 10  bad_debt                 object
 11  liquidation_penalty      object
 12  spot_price               object
 13  funding_payment          object
 14  block_number             int64
 15  timestamp                int64
dtypes: int64(2), object(14)
memory usage: 1.1+ GB

In [17]:
position_changed_events_df

,id,trader,amm,margin,position_notional,exchanged_position_size,fee,position_size_after,realized_pnl,unrealized_pnl_after,bad_debt,liquidation_penalty,spot_price,funding_payment,block_number,timestamp
0,0x06d54c4ad4bfff493051ef548557f4fa0c76fb2dd6787fd665f3b9bf001ad88e-20,0x1a48776f436bcdaa16845a378666cf4ba131eb0f,0x0f346e19f01471c02485df1758cfd3d624e399b4,5552445853546327653508,16657337560638982960524,872709803766812432,16657337560638982960,872709803766812432,0,0,0,0,19120287599999999999991,0,13508290,1607915765
1,0x0e824c5f4e27ba5f29b8791e25e76e732783b25bba4498c380a37efc42478077-6,0x1a48776f436bcdaa16845a378666cf4ba131eb0f,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,6816007869174706369636,20448023607524119108908,34908392150672497289,20448023607524119108,34908392150672497289,0,0,0,0,586786589999999999999,0,13508290,1607915765
2,0xeebbca404104c295253184426d13273fcafcb78867736833c355a2db2eebc747-13,0x1a48776f436bcdaa16845a378666cf4ba131eb0f,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,13632015738349412739272,20448023607524119108908,34786744891928598284,20448023607524119108,69695137042601095573,0,71380545219676979734,0,0,588836755278495176178,0,13508290,1607915765
3,0xe9d804889de5a27a356777a588d6c018e55fa1cae61c6265f11595c4c293a697-6,0x1a48776f436bcdaa16845a378666cf4ba131eb0f,0x0f346e19f01471c02485df1758cfd3d624e399b4,11114599999999999999999,16686462439361017039473,871186558963631015,16686462439361017039,1743896362730443447,0,58249668560559604311,0,0,19187208606599999999964,0,13508954,1607919105
4,0xea81e16520eae51395b4627365487daa2013df876ef3e38254579d1d149b17fd-6,0x1a48776f436bcdaa16845a378666cf4ba131eb0f,0x0f346e19f01471c02485df1758cfd3d624e399b4,0,33343799999999999982175,-1743896362730443447,33343799999999999982,0,-17822,0,0,0,19053600000000000000035,0,13509011,1607919390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9568509,0x5e9ab4772aba966b161f824d5de60f696e409f7b65c20093b4cc0d50dc7baf48-16,0x9fb9fc6e14b006002217b6e48c3de8740e5eab74,0xfcae57db10356fcf76b6476b21ac14c504a45128,21083587357448050278974,249933599999999980000,50489360608512316967,249933599999999980,-7629807965700707797473,-16295076546429225900,-2462465425135274956592,0,0,4950397870513393619,0,21335190,1648429440
9568510,0x641ea1c725b4c7404c256cd97e9e813c2046e492d286a7fbd8c87aec757e52a8-7,0x51fae2fa9d0513f46606a44322cae98975b98f2e,0x7b479a0a816ca33f8eb5a3312d1705a34d2d4c82,498800000000000000000,2494000000000000000000,47865158348061096772,2494000000000000000,47865158348061096772,0,0,0,0,52130675297159723954,0,21335190,1648429440
9568511,0x948ece479a95803d14180410e57e67f99ee0dd52acd2c4ca803b93c82da82ca3-6,0x4700381c4ee01d026dc91a6d4549b77036e5ea9b,0x187c938543f2bde09fe39034fe3ff797a3d35ca0,708000000000000000000,3540000000000000000000,-8198380738007390382414,3540000000000000000,-8198380738007390382414,0,0,0,0,431534268328454689,0,21335191,1648429445
9568512,0xb654796a326f770be8ccd2ae0f58f2a7cff6bef80bad16df2dfd12bf419d6699-13,0xbb2c1c58ea24cacc710952310576d1cea02f7fb7,0xd41025350582674144102b74b8248550580bb869,1462308778132153858733,490599999999999960000,22089705363934043,490599999999999960,133543292654437110,0,41334132679547754444,0,0,22211798815322882149386,-188733566309674049,21335191,1648429445
9568513,0x88a5e9d0cbe8db576fa261fffbec8b163fb03578b102624737c1aa19b9d63352-6,0xe7218b2cacb8001a93334c6734da4781d90bc37a,0x6de775aabeeede8efdb1a257198d56a3ac18c2fd,19161938927610742623493,493599218045007364096,22016821029743783881,493599218045007364,1286016659728754014061,0,203364947184948202030,0,0,22421046255104418503,0,21335192,1648429450

# Collecting required parts

In [6]:
def tx_version_separate(record):
    splitted_id = record['id'].split('-')
    if len(splitted_id) > 1:
        record['id'] = splitted_id[0]
        record['tx_change_version'] = splitted_id[1]
    
    return record

In [7]:
%%time
master_story_funding_rate_part_df = funding_rate_events_df[['id', 'block_number', 'timestamp', 'amm']]
master_story_funding_rate_part_df['origin'] = 'funding rate'
master_story_funding_rate_part_df['tx_change_version'] = np.zeros(len(master_story_funding_rate_part_df))
master_story_funding_rate_part_df = master_story_funding_rate_part_df.apply(lambda record: tx_version_separate(record), axis=1)
master_story_funding_rate_part_df

<timed exec>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Wall time: 20.4 s

,id,block_number,timestamp,amm,origin,tx_change_version
0,0xa397513e00f2cf81f720c4d0f42ddea3b2e5d9be641b4204ce838845748e0d67,13509543,1607922060,0x0f346e19f01471c02485df1758cfd3d624e399b4,funding rate,3
1,0xc159f0f7ef82587f3c6b69374bab00b0d68e4afa41e112d9c1e17d25e4ae90bc,13509543,1607922060,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,funding rate,0
2,0xcd5dc4a5d66a4ab16abb3759aa88c1e6c0e957c75fd725a7f91e9dab373c1628,13510257,1607925660,0x0f346e19f01471c02485df1758cfd3d624e399b4,funding rate,3
3,0xf354a25a613988571ebe671a15dc3ded1cc011e4e500ee4f92e52d1013e77b4b,13510257,1607925660,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,funding rate,0
4,0x7435ec62031e473e1f9c5be987d6b2d1ab271a1b4f52d310c2feef84b85626b5,13510972,1607929260,0x0f346e19f01471c02485df1758cfd3d624e399b4,funding rate,4
...,...,...,...,...,...,...
162955,0xccf3ef04013fe0adff88e50e18fbd5cfe83ca6241bfc1527ef7daaecf6f17812,21335156,1648429260,0x922f28072babe6ea0c0c25ccd367fda0748a5ec7,funding rate,159
162956,0xdc01382260c1685d6d9cbfe6f56357719357e0f42d3f3abe3ebcf60111833c5e,21335156,1648429260,0xeac6cee594edd353351babc145c624849bb70b11,funding rate,166
162957,0xde81e1e692f7e31642803675aa8e9764306b6b38bf67d90e7a960617b05b3174,21335156,1648429260,0xb397389b61cbf3920d297b4ea1847996eb2ac8e8,funding rate,142
162958,0xe8ff282668ac7063b9ff8d8b999b609e6cb39a14e541ca00502a49ece9606608,21335156,1648429260,0x26789518695b56e16f14008c35dc1b281bd5fc0e,funding rate,182
162959,0xfcfa841e86a53a9ccb1a4906acd52fa3d79905dc28de0d9449cabaf05b6f4670,21335156,1648429260,0xf559668108ff57745d5e3077b0a7dd92ffc6300c,funding rate,152

In [8]:
%%time
master_story_liquidations_part_df = liquidation_events_df[['id', 'block_number', 'timestamp', 'amm']]
master_story_liquidations_part_df['origin'] = 'liquidation'
master_story_liquidations_part_df['tx_change_version'] = np.zeros(len(master_story_liquidations_part_df))
master_story_liquidations_part_df = master_story_liquidations_part_df.apply(lambda record: tx_version_separate(record), axis=1)
master_story_liquidations_part_df

<timed exec>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<timed exec>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Wall time: 3.93 s

,id,block_number,timestamp,amm,origin,tx_change_version
0,0xc4889e27cec24728d805bc53ea69ec9771c85bfce825563cc0b55c73ce8bb056,13549293,1608126640,0x0f346e19f01471c02485df1758cfd3d624e399b4,liquidation,6
1,0xad73d00c92a596d4f2ff993a0739ceadf2aebb6f44492fcb6990d2ad112c7ec6,13549484,1608127605,0x0f346e19f01471c02485df1758cfd3d624e399b4,liquidation,6
2,0x6ed6cba6b46fb7fc560dc5c8ee9a1a8d3ec5cdb5ebdfaf8d8eac65086c876b6e,13556301,1608164255,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,liquidation,9
3,0x334432dee6a350dd6b13805babe635160fd4c9f078c6fd9543e5eadce0546602,13556346,1608164505,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,liquidation,16
4,0xa1b2fc6d459f6d32fe405388fe8f766925cd76e58e0da903981bee8623fd0ae2,13563166,1608201405,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,liquidation,6
...,...,...,...,...,...,...
38929,0xcac97f34ca96bdbb202a91d0af0ac8061dea696cc4d1ef6c6d2f61ad8594da79,21334332,1648424915,0x0f346e19f01471c02485df1758cfd3d624e399b4,liquidation,21
38930,0xd3ac193aa02ce2175a123aee3d9c46cf9292e728bdbbf0d266da420cad486242,21334356,1648425040,0x0f346e19f01471c02485df1758cfd3d624e399b4,liquidation,13
38931,0xc58cfe4a6984dc0089239faf0418f47289781061955c12b36cf924b2b122b0a1,21334846,1648427625,0x6de775aabeeede8efdb1a257198d56a3ac18c2fd,liquidation,8
38932,0xbb2bf7e3623b56a421a264b0e2f874dfeb009d10ab58a4182cca366d1f8693b3,21334889,1648427855,0x0f346e19f01471c02485df1758cfd3d624e399b4,liquidation,27
38933,0xab1a4e93c35fa3c52380cfaea47acf589ec96d3c0e4786d5a0ce6048f97d0399,21334943,1648428140,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,liquidation,11

In [9]:
%%time
master_story_margin_changed_part_df = margin_changed_events_df[['id', 'block_number', 'timestamp', 'amm']]
master_story_margin_changed_part_df['origin'] = 'margin change'
master_story_margin_changed_part_df['tx_change_version'] = np.zeros(len(master_story_margin_changed_part_df))
master_story_margin_changed_part_df = master_story_margin_changed_part_df.apply(lambda record: tx_version_separate(record), axis=1)
master_story_margin_changed_part_df

<timed exec>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<timed exec>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Wall time: 6min 7s

,id,block_number,timestamp,amm,origin,tx_change_version
0,0xb359abc9906d7ba2e72fc0339557bc816c722740647dc6e31563b02be819d088,13510771,1607928240,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,margin change,2
1,0x2064d36e819daa34a372e5433ef81dde733d740a79529cf9c2d2df2f4e9d449b,13510776,1607928265,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,margin change,1
2,0x72cc2a320945e33eddbb46b25a892c2be69698f10e838e95990b6ebeab6c3e90,13510801,1607928390,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,margin change,1
3,0x6d177d58cfce6bd165e9f52960e5635f48ae3e5eb42f5496402fe748c7807e2e,13510808,1607928425,0x0f346e19f01471c02485df1758cfd3d624e399b4,margin change,2
4,0xdbc9e3d258653d7afa8a3e7cfd865095dabdc04827e6da6b3812a8d8bfb91966,13510998,1607929395,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,margin change,1
...,...,...,...,...,...,...
3240762,0xc1ef8d0f917c0cc3d4d00d9a991269991a5deaef80fc7d2c9cbd6d515c0564d3,21335175,1648429365,0x922f28072babe6ea0c0c25ccd367fda0748a5ec7,margin change,5
3240763,0xe68178f00f6aa74bc83270083b279d8c8529ac2cd08f50c4d13e2e72f0138694,21335175,1648429365,0x26789518695b56e16f14008c35dc1b281bd5fc0e,margin change,3
3240764,0x1fd7c3f2fd11d5a7b7c923c406a802329b7e72c0b7002e17c7f3f1f4150aa8c3,21335179,1648429385,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,margin change,1
3240765,0x698f3398ca9e5f5c083f1ffd1aacc03cc23f860f863339bc4a4156e5402a1e0f,21335185,1648429415,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,margin change,1
3240766,0x7c1e3dca38a32ad816cbcc970ff108908dc027dbaf70b89859380d95f0ffa19f,21335188,1648429430,0x26789518695b56e16f14008c35dc1b281bd5fc0e,margin change,1

In [10]:
%%time
master_story_position_changes_part_df = position_changed_events_df[['id', 'block_number', 'timestamp', 'amm']]
master_story_position_changes_part_df['origin'] = 'position change'
master_story_position_changes_part_df['tx_change_version'] = np.zeros(len(master_story_position_changes_part_df))
master_story_position_changes_part_df = master_story_position_changes_part_df.apply(lambda record: tx_version_separate(record), axis=1)
master_story_position_changes_part_df

<timed exec>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<timed exec>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Wall time: 17min 20s

,id,block_number,timestamp,amm,origin,tx_change_version
0,0x06d54c4ad4bfff493051ef548557f4fa0c76fb2dd6787fd665f3b9bf001ad88e,13508290,1607915765,0x0f346e19f01471c02485df1758cfd3d624e399b4,position change,20
1,0x0e824c5f4e27ba5f29b8791e25e76e732783b25bba4498c380a37efc42478077,13508290,1607915765,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,position change,6
2,0xeebbca404104c295253184426d13273fcafcb78867736833c355a2db2eebc747,13508290,1607915765,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,position change,13
3,0xe9d804889de5a27a356777a588d6c018e55fa1cae61c6265f11595c4c293a697,13508954,1607919105,0x0f346e19f01471c02485df1758cfd3d624e399b4,position change,6
4,0xea81e16520eae51395b4627365487daa2013df876ef3e38254579d1d149b17fd,13509011,1607919390,0x0f346e19f01471c02485df1758cfd3d624e399b4,position change,6
...,...,...,...,...,...,...
9568509,0x5e9ab4772aba966b161f824d5de60f696e409f7b65c20093b4cc0d50dc7baf48,21335190,1648429440,0xfcae57db10356fcf76b6476b21ac14c504a45128,position change,16
9568510,0x641ea1c725b4c7404c256cd97e9e813c2046e492d286a7fbd8c87aec757e52a8,21335190,1648429440,0x7b479a0a816ca33f8eb5a3312d1705a34d2d4c82,position change,7
9568511,0x948ece479a95803d14180410e57e67f99ee0dd52acd2c4ca803b93c82da82ca3,21335191,1648429445,0x187c938543f2bde09fe39034fe3ff797a3d35ca0,position change,6
9568512,0xb654796a326f770be8ccd2ae0f58f2a7cff6bef80bad16df2dfd12bf419d6699,21335191,1648429445,0xd41025350582674144102b74b8248550580bb869,position change,13
9568513,0x88a5e9d0cbe8db576fa261fffbec8b163fb03578b102624737c1aa19b9d63352,21335192,1648429450,0x6de775aabeeede8efdb1a257198d56a3ac18c2fd,position change,6

In [11]:
master_story_list = [master_story_funding_rate_part_df,
                    master_story_liquidations_part_df,
                    master_story_margin_changed_part_df,
                    master_story_position_changes_part_df]

master_story_df = pd.concat(master_story_list)

In [12]:
master_story_df

,id,block_number,timestamp,amm,origin,tx_change_version
0,0xa397513e00f2cf81f720c4d0f42ddea3b2e5d9be641b4204ce838845748e0d67,13509543,1607922060,0x0f346e19f01471c02485df1758cfd3d624e399b4,funding rate,3
1,0xc159f0f7ef82587f3c6b69374bab00b0d68e4afa41e112d9c1e17d25e4ae90bc,13509543,1607922060,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,funding rate,0
2,0xcd5dc4a5d66a4ab16abb3759aa88c1e6c0e957c75fd725a7f91e9dab373c1628,13510257,1607925660,0x0f346e19f01471c02485df1758cfd3d624e399b4,funding rate,3
3,0xf354a25a613988571ebe671a15dc3ded1cc011e4e500ee4f92e52d1013e77b4b,13510257,1607925660,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,funding rate,0
4,0x7435ec62031e473e1f9c5be987d6b2d1ab271a1b4f52d310c2feef84b85626b5,13510972,1607929260,0x0f346e19f01471c02485df1758cfd3d624e399b4,funding rate,4
...,...,...,...,...,...,...
9568509,0x5e9ab4772aba966b161f824d5de60f696e409f7b65c20093b4cc0d50dc7baf48,21335190,1648429440,0xfcae57db10356fcf76b6476b21ac14c504a45128,position change,16
9568510,0x641ea1c725b4c7404c256cd97e9e813c2046e492d286a7fbd8c87aec757e52a8,21335190,1648429440,0x7b479a0a816ca33f8eb5a3312d1705a34d2d4c82,position change,7
9568511,0x948ece479a95803d14180410e57e67f99ee0dd52acd2c4ca803b93c82da82ca3,21335191,1648429445,0x187c938543f2bde09fe39034fe3ff797a3d35ca0,position change,6
9568512,0xb654796a326f770be8ccd2ae0f58f2a7cff6bef80bad16df2dfd12bf419d6699,21335191,1648429445,0xd41025350582674144102b74b8248550580bb869,position change,13
9568513,0x88a5e9d0cbe8db576fa261fffbec8b163fb03578b102624737c1aa19b9d63352,21335192,1648429450,0x6de775aabeeede8efdb1a257198d56a3ac18c2fd,position change,6

In [13]:
master_story_df.sort_values(by=['block_number', 'tx_change_version'], inplace=True)
master_story_df.reset_index(inplace=True)

In [37]:
master_story_df.drop(columns=['index'], inplace=True)

In [15]:
master_story_df

,index,id,block_number,timestamp,amm,origin,tx_change_version
0,2,0xeebbca404104c295253184426d13273fcafcb78867736833c355a2db2eebc747,13508290,1607915765,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,position change,13
1,0,0x06d54c4ad4bfff493051ef548557f4fa0c76fb2dd6787fd665f3b9bf001ad88e,13508290,1607915765,0x0f346e19f01471c02485df1758cfd3d624e399b4,position change,20
2,1,0x0e824c5f4e27ba5f29b8791e25e76e732783b25bba4498c380a37efc42478077,13508290,1607915765,0x8d22f1a9dce724d8c1b4c688d75f17a2fe2d32df,position change,6
3,3,0xe9d804889de5a27a356777a588d6c018e55fa1cae61c6265f11595c4c293a697,13508954,1607919105,0x0f346e19f01471c02485df1758cfd3d624e399b4,position change,6
4,4,0xea81e16520eae51395b4627365487daa2013df876ef3e38254579d1d149b17fd,13509011,1607919390,0x0f346e19f01471c02485df1758cfd3d624e399b4,position change,6
...,...,...,...,...,...,...,...
13011170,9568509,0x5e9ab4772aba966b161f824d5de60f696e409f7b65c20093b4cc0d50dc7baf48,21335190,1648429440,0xfcae57db10356fcf76b6476b21ac14c504a45128,position change,16
13011171,9568510,0x641ea1c725b4c7404c256cd97e9e813c2046e492d286a7fbd8c87aec757e52a8,21335190,1648429440,0x7b479a0a816ca33f8eb5a3312d1705a34d2d4c82,position change,7
13011172,9568512,0xb654796a326f770be8ccd2ae0f58f2a7cff6bef80bad16df2dfd12bf419d6699,21335191,1648429445,0xd41025350582674144102b74b8248550580bb869,position change,13
13011173,9568511,0x948ece479a95803d14180410e57e67f99ee0dd52acd2c4ca803b93c82da82ca3,21335191,1648429445,0x187c938543f2bde09fe39034fe3ff797a3d35ca0,position change,6
13011174,9568513,0x88a5e9d0cbe8db576fa261fffbec8b163fb03578b102624737c1aa19b9d63352,21335192,1648429450,0x6de775aabeeede8efdb1a257198d56a3ac18c2fd,position change,6

In [14]:
master_story_df.to_csv("master_story_df.csv")