In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Current task of the presented notebook is in connecting information from several tables to form a "master" one where will be presented complete overview of the activity performed by the trader. Considering that here will be performed several steps:

1. Setting tables which will be concatenated to form a complete overview for trader with sort of the activity based on the block number and log index in the block (sorting by time will not work, because timestamps are covering time of block, not exact time of transaction);
2. Setting columns that will be taken from other tables and connected to the "master" table;
3. Save of the master table;
4. Visualization of the "master" data considering different columns

# Setting up the tables to concatenate

## Position changes

In [32]:
tokens_addresses_to_names_dict = {
    "0x86f1e0420c26a858fc203a3645dd1a36868f18e5": "vBTC",
    "0x8c835dfaa34e2ae61775e80ee29e2c724c6ae2bb": "vETH",
    "0x5faa136fc58b6136ffdaeaac320076c4865c070f": "vAVAX",
    "0xb24f50dd9918934ab2228be7a097411ca28f6c14": "vLUNA",
    "0x151bb01c79f4516c233948d69dae39869bccb737": "vSOL",
    "0x7161c3416e08abaa5cd38e68d9a28e43a694e037": "vCRV",
    "0x333b1ea429a88d0dd48ce7c06c16609cd76f43a8": "vSAND",
    "0x2f198182ec54469195a4a06262a9431a42462373": "vLINK",
    "0x5f714b5347f0b5de9f9598e39840e176ce889b9c": "vATOM",
    "0x77d0cc9568605bfff32f918c8ffaa53f72901416": "vONE",
    "0x3fb3282e3ba34a0bff94845f1800eb93cc6850d4": "vNEAR",
    "0x2db8d2db86ca3a4c7040e778244451776570359b": "vFTM",
    "0x7eada83e15acd08d22ad85a1dce92e5a257acb92": "vFLOW",
    "0xb6599bd362120dc70d48409b8a08888807050700": "vBNB",
    "0x9482aafdced6b899626f465e1fa0cf1b1418d797": "vPERP",
    "0xbe5de48197fc974600929196239e264ecb703ee8": "vMATIC",
    "0x34235c8489b06482a99bb7fcab6d7c467b92d248": "vAAVE",
    "0x9d34f1d15c22e4c0924804e2a38cbe93dfb84bc2": "vAPE"
}

In [33]:
position_changes_df = pd.read_csv("position_changes.csv")
position_changes_df["time"] = pd.to_datetime(position_changes_df["timestamp"], unit='s')
position_changes_df["pool_name"] = position_changes_df["base_token"].replace(tokens_addresses_to_names_dict)
position_changes_df = position_changes_df.sort_values("block_number_log_index")
position_changes_df = position_changes_df.reset_index()
position_changes_df.drop(columns=["Unnamed: 0", "base_token", "from_function_signature", "block_number", "id", "index"], inplace=True)
position_changes_df

,tx_hash,trader,exchanged_position_size,exchanged_position_notional,fee,open_notional,realized_pnl,position_size_after,swapped_price,entry_price_after,market_price_after,block_number_log_index,timestamp,time,pool_name
0,0x9a9ef69c82d19bde6a2794c5de22bbb02dd3b2b4f048...,0x9c1e0c67aa30c063f341885b12cb81cc94613fc7,0.055178,-2997.000000,3.000000,-3000.000000,0.0,0.055178,54315.297418,54369.667085,54334.893904,515560007,1638001140,2021-11-27 08:19:00,vBTC
1,0x0e085ae4b7c345ee6de6d67f16c8c127a694d1c9f27f...,0x9c1e0c67aa30c063f341885b12cb81cc94613fc7,0.729828,-2997.000000,3.000000,-3000.000000,0.0,0.729828,4106.445744,4110.556300,4108.035203,515571005,1638001140,2021-11-27 08:19:00,vETH
2,0x8699da2d3dee9c704dbf13705c75524e618b2a83c8c3...,0x9c1e0c67aa30c063f341885b12cb81cc94613fc7,0.055138,-2997.000000,3.000000,-6000.000000,0.0,0.110316,54354.490389,54389.276112,54374.093942,515582004,1638001140,2021-11-27 08:19:00,vBTC
3,0x548dd8a96b9faa92066283339832e380fd506f4ebc94...,0x9c1e0c67aa30c063f341885b12cb81cc94613fc7,0.729264,-2997.000000,3.000000,-6000.000000,0.0,1.459092,4109.624663,4112.146735,4111.214738,515584004,1638001140,2021-11-27 08:19:00,vETH
4,0x0ccfa4751250a5374b5d28823a1011987b833f71a1ce...,0x9c1e0c67aa30c063f341885b12cb81cc94613fc7,0.055098,-2997.000000,3.000000,-9000.000000,0.0,0.165414,54393.697496,54408.885139,54413.308117,515587004,1638001140,2021-11-27 08:19:00,vBTC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3371091,0xf2d260d060e194efe9456366a187f8b1bbadede2112a...,0x66465ad392942e78f8147ae565a43f174071822b,-63.016538,1007.767544,1.007768,77543.167127,0.0,-4785.063498,15.992112,16.205254,15.968758,12161192007,1655487520,2022-06-17 17:38:40,vAVAX
3371092,0x70f96597f01dd545840b697b13056240e0b87599cb06...,0x31789f360b9aab20837a35944904deb540533357,-5.821204,1250.535778,1.250536,28511.176773,0.0,-132.045808,214.824254,215.918833,214.596023,12161203007,1655487554,2022-06-17 17:39:14,vBNB
3371093,0x57f2cd5a07c1e96d84b1b1f4b479e0e5e498f1edc445...,0xdab8a2e0b213ec8447d4f7cdb783d53ed3428b7a,-3419.000000,806.897384,0.806897,806.090487,0.0,-3419.000000,0.236004,0.235768,0.235708,12161205005,1655487554,2022-06-17 17:39:14,vFTM
3371094,0xf26360ff610d3f5db14d31d97a8d0c5158741b3f2268...,0x0cbdd4a3861ba3b2e0f68cea10209a606d38aeca,-1220.524515,750.778051,0.750778,74113.308142,0.0,-122785.420591,0.615127,0.603600,0.614201,12161208007,1655487554,2022-06-17 17:39:14,vPERP
3371095,0x92be5d897f613e47643bca8f54762236ecf9960f8f85...,0x6f2ddd6d04aa4ebaa6e9529e8a1b4062a2716281,-279.070738,1000.148840,1.000149,90888.188540,0.0,-25408.278041,3.583854,3.577109,3.578205,12161213007,1655487554,2022-06-17 17:39:14,vAPE

Out of the presented columns there will be used for "master" table ```tx_hash, trader, exchanged_position_size, fee, open_notional, realized_pnl, position_size_after, swapped_price, market_price_after, block_number_log_index, timestamp, time, pool_name``` (13 columns)

## Funding payments

In [34]:
funding_payments_df = pd.read_csv("funding_payments.csv")
funding_payments_df["pool_name"] = funding_payments_df["base_token"].replace(tokens_addresses_to_names_dict)
funding_payments_df = funding_payments_df.sort_values("block_number_log_index")
funding_payments_df = funding_payments_df.reset_index()
funding_payments_df["time"] = pd.to_datetime(funding_payments_df["timestamp"], unit='s')
funding_payments_df.drop(columns=["Unnamed: 0", "block_number", "index", "base_token", "id"], inplace=True)
funding_payments_df

,tx_hash,funding_payment,block_number_log_index,timestamp,time,pool_name
0,0x9a9ef69c82d19bde6a2794c5de22bbb02dd3b2b4f048...,0.000000,515560002,1638001140,2021-11-27 08:19:00,vBTC
1,0x9e2a266e4bb63ea7baaa53522ed51d7dc414df095e07...,0.000000,515624002,1638001245,2021-11-27 08:20:45,vBTC
2,0x79655d30e251fa6cd88d1bdeb0a3bc11d2316b6dd5ff...,0.000000,515740002,1638001497,2021-11-27 08:24:57,vBTC
3,0x6cf3b7acabc36423f5c80006028ef5144c006fecfb36...,0.000000,516486001,1638003992,2021-11-27 09:06:32,vETH
4,0x1f9cbc33e7ba0bb63fe8431c7356c19e2a8529a8277b...,0.021516,516538002,1638004141,2021-11-27 09:09:01,vETH
...,...,...,...,...,...,...
2346915,0x2ad772a2702c694c7e07f598877d5cbceabc2c4d0f34...,0.061829,12061841002,1655402426,2022-06-16 18:00:26,vETH
2346916,0x77891843790367fc904040d2ed027e091431e3e6501b...,1.453814,12061852002,1655402442,2022-06-16 18:00:42,vPERP
2346917,0x1f7d56c26682028bb931df302fb5b0a66f9fc6af079b...,5.211893,12061856002,1655402442,2022-06-16 18:00:42,vNEAR
2346918,0xed6fb6aacf469dab951adf3508b5b1c1303d6ef6fcd4...,-65.119290,12061868002,1655402457,2022-06-16 18:00:57,vBTC
2346919,0xfd3c2222defadd82c9b1d9fcf38bafbced65f5fa7c8f...,-38.409706,12061881002,1655402472,2022-06-16 18:01:12,vFTM

This table will be concatenated with the "master" table by inner join of the ```tx_hash, block_number_log_index, timestamp, time, pool_name``` columns (5 columns) and add column ```funding_payment```

## Funding updates

In [35]:
funding_updates_df = pd.read_csv("funding_updates.csv")
funding_updates_df["pool_name"] = funding_updates_df["base_token"].replace(tokens_addresses_to_names_dict)
funding_updates_df["time"] = pd.to_datetime(funding_updates_df["timestamp"], unit='s')
funding_updates_df = funding_updates_df.sort_values("block_number_log_index")
funding_updates_df = funding_updates_df.reset_index()
funding_updates_df.drop(columns=["Unnamed: 0", "base_token", "block_number", "index", "id"], inplace=True)
funding_updates_df

,tx_hash,mark_twap,index_twap,daily_funding_rate,block_number_log_index,timestamp,time,pool_name
0,0xec1e410b931f920c4aa3ae105e63463142b310fbe959...,54295.708000,55072.675000,-0.014108,515552000,1638000985,2021-11-27 08:16:25,vBTC
1,0x7dba9c535f6c595ab39eeec818d89b34783442bafa81...,4104.856899,4167.914502,-0.015129,515554000,1638000985,2021-11-27 08:16:25,vETH
2,0x9a9ef69c82d19bde6a2794c5de22bbb02dd3b2b4f048...,54295.708000,55072.675000,-0.014108,515560000,1638001140,2021-11-27 08:19:00,vBTC
3,0x0e085ae4b7c345ee6de6d67f16c8c127a694d1c9f27f...,4104.856899,4167.914502,-0.015129,515571000,1638001140,2021-11-27 08:19:00,vETH
4,0x4d8968cdbf0802526b673fa96d973dda0361ed6ccccb...,4120.722610,4167.914502,-0.011323,515621000,1638001245,2021-11-27 08:20:45,vETH
...,...,...,...,...,...,...,...,...
1754643,0x317fa1e2410b0ea6bcc396894904adb90090333725a2...,0.208478,0.207992,0.002335,11551962000,1655116885,2022-06-13 10:41:25,vFTM
1754644,0x4e0dd2c266b013e474d827249180bf9901c7ccb581f9...,6.152812,6.148795,0.000653,11551974000,1655116885,2022-06-13 10:41:25,vATOM
1754645,0x130dd656d3218a673a2c72f46b87e7dba7d4b6f474a8...,227.040575,226.388371,0.002881,11551982000,1655116885,2022-06-13 10:41:25,vBNB
1754646,0x8cf65f035292fd583a444625d4cc83cc557cc6ea5028...,3.252230,3.242339,0.003051,11551986000,1655116885,2022-06-13 10:41:25,vNEAR
1754647,0x0b6c4283a95b618e53ab7fe9fa902606e5b9f390d9e1...,59.411973,59.447355,-0.000595,11551995000,1655116885,2022-06-13 10:41:25,vAAVE

This table will be concatenated with the "master" table via inner join of columns ```tx_hash, block_number_log_index, timestamp, time, pool_name``` and add new columns to the "master" ```mark_twap, index_twap, daily_funding_rate``` (3 columns)

## Deposits

In [36]:
deposits_df = pd.read_csv("deposits.csv")
deposits_df["time"] = pd.to_datetime(deposits_df["timestamp"], unit='s')
deposits_df.drop(columns=["Unnamed: 0", "id", "collateral_token", "block_number"], inplace=True)
deposits_df = deposits_df.rename(columns={"amount": "deposit"})
deposits_df

,tx_hash,trader,deposit,block_number_log_index,timestamp,time
0,0xe3b75b08f5bc08eb7e2de960dffbe88df1c3e2de4bd2...,0x9c1e0c67aa30c063f341885b12cb81cc94613fc7,250000.000000,515551002,1638000985,2021-11-27 08:16:25
1,0x7c0d88b53e0f416e9643d4c1d287df62337dc17b935d...,0x98029c23e4a554989c280de7fcb1c2ededf2b17f,500.000000,516284002,1638002723,2021-11-27 08:45:23
2,0xe17370b8c373f24c02df5effe94220e12c85cbfa6815...,0x1313817a82545e29764281f51f6255619753235d,500.000000,516348002,1638003246,2021-11-27 08:54:06
3,0x76d948abee1a1de89b947876dec3941d7a7d7e3860d5...,0xd087966b4d2b1841c88b4d62b407d5ef1a465ac3,500.000000,516415002,1638003538,2021-11-27 08:58:58
4,0x02288555584fe8d00e6e4c596d286544647666a01eed...,0xc9735c7e0015fc9719f28306f90e530420f9b4ef,500.000000,516446002,1638003768,2021-11-27 09:02:48
...,...,...,...,...,...,...
28663,0x07178e6762a5528458e7c4de50e3b0d7dd3da39bfd60...,0xff058c99568e0f753b960f1d0ac7830bdff1a51a,11860.000000,11549594002,1655115884,2022-06-13 10:24:44
28664,0xf2f67743e382bce6c8dd1935957e86e6d8b327030e9d...,0x94bfc92633da476b10bdd5d0151cda8adefc5468,250.000000,11549897002,1655116038,2022-06-13 10:27:18
28665,0x78ad7883219c42cbe77174c726df4433542810cd6e63...,0x927eb0dbc5c3fd172fdfa72d563f71612ecb6122,16180.775246,11552591016,1655117128,2022-06-13 10:45:28
28666,0x42457b161a1631d0a8aea7796adc4814af5b30eecd11...,0x927eb0dbc5c3fd172fdfa72d563f71612ecb6122,16258.897008,11552754017,1655117188,2022-06-13 10:46:28
28667,0x4faf1f14f10927afa315282bf0da21cf8fcb1bc10cb8...,0x4b5aeeb5fd6b9d7febf8aec97bf5717423f8cc89,601.021864,11553648002,1655117428,2022-06-13 10:50:28

In [37]:
deposits_df.loc[0].tx_hash

'0xe3b75b08f5bc08eb7e2de960dffbe88df1c3e2de4bd2997120bd0748281d4e6c'

Out of the presented columns there are for inner join ```tx_hash, trader, block_number_log_index, timestamp, time``` and there is one appendable column to the "master" called ```amount```

## Withdraws

In [38]:
withdraws_df = pd.read_csv("withdraws.csv")
withdraws_df.drop(columns=["Unnamed: 0", "collateral_token", "id", "block_number"], inplace=True)
withdraws_df = withdraws_df.rename(columns={"amount": "withdraw"})
withdraws_df

,tx_hash,trader,withdraw,block_number_log_index,timestamp,time
0,0x523a7a44bc2ccee84ae8337949db01ef4b5268f420e0...,0x499166d1a71fed3b490ddb0591f4ae14c1031993,173.323015,575084001,1638150257,2021-11-29 01:44:17
1,0x29583b942fdaf2f39c3ef38fbc18e6ade9c7edc73715...,0x4ffef86586e730bd8e848708124c105d8f01ba7d,1418.636005,578836001,1638166466,2021-11-29 06:14:26
2,0x6b7a65b92feaaa0e61acda8d53ff7bffd97c5353a796...,0x2441434f47e511a13714d8f7ae60dd923b1cfadd,681.426360,578875001,1638166558,2021-11-29 06:15:58
3,0x7f694a7478ca8f244e9764c3561de318bb48d9c9edb4...,0x27fee0c6356c2f27e646d73f2256d30331c6a001,499.951236,578895001,1638166558,2021-11-29 06:15:58
4,0x85b233912d3f34b064fb1b0396878787f1f9ae6c33f6...,0xf2cd72adf27aea9808152a93dab9092e89163fb5,688.383929,579467001,1638168684,2021-11-29 06:51:24
...,...,...,...,...,...,...
17219,0xb653b35983d773ef0dc416ff93cb483f2e9005681a2f...,0x8bf61529a436c16b9d0dff22ae9a712357594a02,25000.000000,11551580005,1655116765,2022-06-13 10:39:25
17220,0x8d5f45c8e6386641e16dfed97f0c35cec6e027844c97...,0x0be27c140f9bdad3474beaff0a413ec7e19e9b93,5054.739452,11551853021,1655116840,2022-06-13 10:40:40
17221,0xd63e586dcb3aea1e8fe87bfa7ef6a504e479cf4c20f9...,0xc9ea06315038afcb52685481909be0a02dd3f206,10000.000000,11552311013,1655117005,2022-06-13 10:43:25
17222,0x38e4b1078bdc79c5e93f817fd8307273c9bb4889903b...,0xb475bc2bed71c15c1cddd94d954b27f3354ac223,7.528969,11553946001,1655117642,2022-06-13 10:54:02
17223,0xe98b8c1ed3cd53a3fe5b674d461dd34cf1ecd44cc0d5...,0x23443c67362b06efd93ec22368d9ec889433eb9d,1443.247746,11555684001,1655118400,2022-06-13 11:06:40

From the current table there will be used for inner join columns ```tx_hash, trader, block_number_log_index, timestamp, time``` and for appending to the "master" table there will be only column ```amount```

## Position liquidations

In [39]:
position_liquidations_df = pd.read_csv("position_liquidations.csv")
position_liquidations_df["pool_name"] = position_liquidations_df["base_token"].replace(tokens_addresses_to_names_dict)
position_liquidations_df.drop(columns=["Unnamed: 0", "base_token"], inplace=True)
position_liquidations_df

,tx_hash,trader,liquidator,liquidation_fee,position_size_abs,position_notional_abs,block_number,timestamp,time,pool_name
0,0xf29899730b11a5753acfd2aa76323a00cc5138bc0432...,0x98029c23e4a554989c280de7fcb1c2ededf2b17f,0x5b3b3ed2bc7e643f6b558237e7c488e6b32eed80,48.873227,0.453003,1954.929064,571747,1638141748,2021-11-28 23:22:28,vETH
1,0x94eec0d2531abdd25a4114cff480dda1d42e1b5624af...,0x499166d1a71fed3b490ddb0591f4ae14c1031993,0x4680cca73f815b583a201afef4b70451fb53b7af,138.828968,0.096288,5553.158726,572724,1638144236,2021-11-29 00:03:56,vBTC
2,0x5dfcb2f5856e4df95701ac6142b20e7e491314119693...,0x35952141922ee99a04e016c967c3f0ad589ea958,0x5b3b3ed2bc7e643f6b558237e7c488e6b32eed80,15.017667,0.010330,600.706678,573466,1638145638,2021-11-29 00:27:18,vBTC
3,0xc8f54890f82e3b91f802c221765b025a8c119c498fbb...,0xd087966b4d2b1841c88b4d62b407d5ef1a465ac3,0x5b3b3ed2bc7e643f6b558237e7c488e6b32eed80,121.233376,0.083333,4849.335035,573632,1638145930,2021-11-29 00:32:10,vBTC
4,0x71bfc81fe97adc1e8d4f783ec56fd9fa6bc1d024602c...,0x35952141922ee99a04e016c967c3f0ad589ea958,0x5b3b3ed2bc7e643f6b558237e7c488e6b32eed80,66.776190,0.608888,2671.047610,574411,1638147791,2021-11-29 01:03:11,vETH
...,...,...,...,...,...,...,...,...,...,...
4246,0x0c4a49fe3343c15a84d52b3913a9f52fd45002fb5d21...,0x7a0ef482134aa53468850a7b117eca38a6a3003d,0x38374d7a281b4f1e3cf527b39c65eae4c00ec5b1,0.324909,0.011818,12.996355,12015144,1655376082,2022-06-16 10:41:22,vETH
4247,0x6fd0f0047bfe5101b175f9864b0f119eb2295fb7a86b...,0x697ccd97c8419ebba7347cef03a0cd02804ebf54,0x2f06b6fbd4ce2139e01a1bee7154b79f898c0dd4,134.090920,92.986214,5363.636783,12015288,1655376188,2022-06-16 10:43:08,vAAVE
4248,0xbd5aba8f7f82464bfde039c9d97d8fedecb112b8ecab...,0x9327b6729b28c3b91cc88bb556edf56eeb699d4a,0x2f06b6fbd4ce2139e01a1bee7154b79f898c0dd4,543.927002,19.652924,21757.080074,12039656,1655389045,2022-06-16 14:17:25,vETH
4249,0x5ccef06fbd002df5d1486974e63c592d45fa9644ea48...,0x3f60008dfd0efc03f476d9b489d6c5b13b3ebf2c,0x04c39026eaab0b7f0a46c26bb6a278f31ea8dc93,3.466823,0.130428,138.672904,12082313,1655420967,2022-06-16 23:09:27,vETH
4250,0xe93435ad67a54fc177907a92da3784bd235c6b840ce5...,0xeab7a90c520f230fe21a8a9124790f7f93c5b4ca,0x04c39026eaab0b7f0a46c26bb6a278f31ea8dc93,3.507434,4.724502,140.297379,12082725,1655421349,2022-06-16 23:15:49,vSOL

There are columns for performing inner join to the "master" table: ```tx_hash, trader, liquidator, timestamp, time, pool_name```

Appendable columns to the "master" table will be: ```liquidation_fee, position_size_abs, position_notional_abs``` (3 columns)

# Forming a master table

In [40]:
master_trader_df = position_changes_df
print(len(position_changes_df) + len(funding_payments_df) + len(funding_updates_df) + len(deposits_df) + 
      len(withdraws_df) + len(position_liquidations_df))

#   funding payments
master_trader_df = pd.concat([master_trader_df, funding_payments_df])
master_trader_df.sort_values("block_number_log_index", inplace=True)
master_trader_df = master_trader_df.reset_index()
master_trader_df.drop(columns=["index"], inplace=True)

#   funding updates
master_trader_df = pd.concat([master_trader_df, funding_updates_df])
master_trader_df.sort_values("block_number_log_index", inplace=True)
master_trader_df = master_trader_df.reset_index()
master_trader_df.drop(columns=["index"], inplace=True)

#   deposits
master_trader_df = pd.concat([master_trader_df, deposits_df])
master_trader_df.sort_values("block_number_log_index", inplace=True)
master_trader_df = master_trader_df.reset_index()
master_trader_df.drop(columns=["index"], inplace=True)

#   withdraws
master_trader_df = pd.concat([master_trader_df, withdraws_df])
master_trader_df.sort_values("block_number_log_index", inplace=True)
master_trader_df = master_trader_df.reset_index()
master_trader_df.drop(columns=["index"], inplace=True)

#   position liquidations
master_trader_df = pd.concat([master_trader_df, position_liquidations_df])
master_trader_df.sort_values(["timestamp", "block_number_log_index"], inplace=True)
master_trader_df = master_trader_df.reset_index()
master_trader_df.drop(columns=["index"], inplace=True)
master_trader_df

7522807

,tx_hash,trader,exchanged_position_size,exchanged_position_notional,fee,open_notional,realized_pnl,position_size_after,swapped_price,entry_price_after,...,mark_twap,index_twap,daily_funding_rate,deposit,withdraw,liquidator,liquidation_fee,position_size_abs,position_notional_abs,block_number
0,0xe3b75b08f5bc08eb7e2de960dffbe88df1c3e2de4bd2...,0x9c1e0c67aa30c063f341885b12cb81cc94613fc7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,250000.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0xec1e410b931f920c4aa3ae105e63463142b310fbe959...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,54295.708000,55072.675000,-0.014108,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0x7dba9c535f6c595ab39eeec818d89b34783442bafa81...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4104.856899,4167.914502,-0.015129,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0x9a9ef69c82d19bde6a2794c5de22bbb02dd3b2b4f048...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,54295.708000,55072.675000,-0.014108,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0x9a9ef69c82d19bde6a2794c5de22bbb02dd3b2b4f048...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7522802,0xf2d260d060e194efe9456366a187f8b1bbadede2112a...,0x66465ad392942e78f8147ae565a43f174071822b,-63.016538,1007.767544,1.007768,77543.167127,0.0,-4785.063498,15.992112,16.205254,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7522803,0x70f96597f01dd545840b697b13056240e0b87599cb06...,0x31789f360b9aab20837a35944904deb540533357,-5.821204,1250.535778,1.250536,28511.176773,0.0,-132.045808,214.824254,215.918833,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7522804,0x57f2cd5a07c1e96d84b1b1f4b479e0e5e498f1edc445...,0xdab8a2e0b213ec8447d4f7cdb783d53ed3428b7a,-3419.000000,806.897384,0.806897,806.090487,0.0,-3419.000000,0.236004,0.235768,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7522805,0xf26360ff610d3f5db14d31d97a8d0c5158741b3f2268...,0x0cbdd4a3861ba3b2e0f68cea10209a606d38aeca,-1220.524515,750.778051,0.750778,74113.308142,0.0,-122785.420591,0.615127,0.603600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7522806,0x92be5d897f613e47643bca8f54762236ecf9960f8f85...,0x6f2ddd6d04aa4ebaa6e9529e8a1b4062a2716281,-279.070738,1000.148840,1.000149,90888.188540,0.0,-25408.278041,3.583854,3.577109,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
master_trader_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7522807 entries, 0 to 7522806
Data columns (total 26 columns):
 #   Column                       Dtype
---  ------                       -----
 0   tx_hash                      object
 1   trader                       object
 2   exchanged_position_size      float64
 3   exchanged_position_notional  float64
 4   fee                          float64
 5   open_notional                float64
 6   realized_pnl                 float64
 7   position_size_after          float64
 8   swapped_price                float64
 9   entry_price_after            float64
 10  market_price_after           float64
 11  block_number_log_index       float64
 12  timestamp                    int64
 13  time                         object
 14  pool_name                    object
 15  funding_payment              float64
 16  mark_twap                    float64
 17  index_twap                   float64
 18  daily_funding_rate           float64
 19  deposit                      float64
 20  withdraw                     float64
 21  liquidator                   object
 22  liquidation_fee              float64
 23  position_size_abs            float64
 24  position_notional_abs        float64
 25  block_number                 float64
dtypes: float64(20), int64(1), object(5)
memory usage: 1.5+ GB

In [42]:
master_trader_df.describe().T

,count,mean,std,min,25%,50%,75%,max
exchanged_position_size,3371096.0,-1.145799e+00,1.299809e+04,-5.390345e+06,-1.162416e+02,-6.803914e-02,9.985121e+01,4.551855e+06
exchanged_position_notional,3371096.0,5.469362e+00,9.485866e+03,-2.146352e+06,-2.097900e+03,4.097203e+01,2.108611e+03,1.739286e+06
fee,3371096.0,3.106018e+00,4.250538e+00,0.000000e+00,9.973946e-01,2.042042e+00,3.995878e+00,6.447358e+02
open_notional,3371096.0,3.120037e+04,1.638121e+05,-2.483868e+06,-8.450600e+03,8.595450e+03,7.113644e+04,4.099120e+06
realized_pnl,3371096.0,-2.252611e+00,2.920618e+02,-1.982351e+05,-1.407664e-01,0.000000e+00,0.000000e+00,4.725508e+04
position_size_after,3371096.0,-1.796745e+04,3.430900e+05,-8.125693e+06,-5.069685e+03,-8.165085e+01,2.212671e+02,8.638332e+06
swapped_price,3371096.0,2.067413e+03,8.204226e+03,0.000000e+00,2.495694e+00,1.563260e+01,9.092479e+01,5.925279e+04
entry_price_after,3371096.0,1.111347e+04,1.687611e+07,0.000000e+00,1.823160e+00,1.324330e+01,8.738689e+01,3.098546e+10
market_price_after,3371096.0,2.070676e+03,8.210026e+03,1.654079e-02,2.515480e+00,1.567431e+01,9.099513e+01,5.926332e+04
block_number_log_index,7518556.0,6.561257e+09,2.421109e+09,5.155510e+08,4.656596e+09,6.246387e+09,8.187324e+09,1.216121e+10
timestamp,7522807.0,1.650100e+09,3.366637e+06,1.638001e+09,1.647829e+09,1.650641e+09,1.652470e+09,1.655488e+09
funding_payment,2346920.0,-1.241704e-01,7.858499e+01,-1.422811e+04,-5.128310e-02,-5.582803e-05,4.453410e-02,1.056781e+05
mark_twap,1754648.0,1.904664e+03,7.989104e+03,1.715275e-02,2.248941e+00,1.307199e+01,8.627821e+01,5.923990e+04
index_twap,1754648.0,1.903670e+03,7.985776e+03,4.449570e-03,2.249747e+00,1.306123e+01,8.630896e+01,5.902567e+04
daily_funding_rate,1754648.0,6.261604e-04,8.708185e-02,-3.253081e-01,-2.198185e-03,-3.393911e-04,1.131370e-03,1.785056e+01
deposit,28668.0,3.546935e+03,5.797019e+04,9.829000e-07,1.000000e+01,1.700000e+01,2.137601e+02,5.000000e+06
withdraw,17224.0,4.045397e+03,6.938162e+04,0.000000e+00,1.271712e+01,1.000000e+02,6.300565e+02,7.560731e+06
liquidation_fee,4251.0,7.030301e+01,5.309297e+02,5.547257e-06,1.747383e+00,2.427663e+00,1.265378e+01,1.611840e+04
position_size_abs,4251.0,3.288609e+02,2.373460e+03,9.534199e-08,2.563524e-02,3.527379e-02,2.433715e+00,5.639131e+04
position_notional_abs,4251.0,2.812120e+03,2.123719e+04,2.218903e-04,6.989531e+01,9.710652e+01,5.061512e+02,6.447358e+05
block_number,4251.0,5.970827e+06,2.987578e+06,5.717470e+05,4.356802e+06,4.361556e+06,7.840283e+06,1.208272e+07

In [43]:
master_trader_df.to_csv("master_trader.csv")

In [44]:
master_trader_df["block_number_log_index"][:20]

0     515551002.0
1     515552000.0
2     515554000.0
3     515560000.0
4     515560002.0
5     515560007.0
6     515571000.0
7     515571005.0
8     515582004.0
9     515584004.0
10    515587004.0
11    515589004.0
12    515592004.0
13    515594004.0
14    515608004.0
15    515609004.0
16    515619004.0
17    515621000.0
18    515621005.0
19    515624000.0
Name: block_number_log_index, dtype: float64